server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapperLocation: classpath:mapper/*.xml
#  type-aliases-package: com.strive.springcloud.entities

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka