server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  server:
    #自我保护机制关闭
    enable-self-preservation: true
    #心跳时间间隔
    eviction-interval-timer-in-ms: 6000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #集群指向其他eureka
      defaultZone: http://eureka7001.com:7001/eureka

